### ISSUE TITLE
Auto exposed stopped working since 2026.6.0

### ISSUE THREAD

**Issue by DewGew** [Connum/hass-ga-autoexpose#10]
This component dont work in 2026.6.0. 
`cannot import name 'CLOUD_NEVER_EXPOSED_ENTITIES' from 'homeassistant.const'` 

Home assistant removed the constant from ../homeassistant/const.py

[https://github.com/home-assistant/core/pull/171933](https://github.com/home-assistant/core/pull/171933)

**Comment by ajvandr** [comment]
I've commented out the lines that refer to the missing constant and it is working again.
